### ISSUE TITLE
Différence entre les fichiers CSV dans /inst et /inst/csv

### ISSUE THREAD

**Issue by 68498468** [benjaminguinaudeau/csatimer#2]
Les fichiers suivant sont présent dans deux répertoires différents, /inst et /inst/csv
- 2017.csv
- 2018.csv
- 2019.csv
- 2020.csv 
- 2021.csv 

Ceux présent dans /inst/csv ont été mis à jour il y a 2 jours, mais pas ceux présent dans /inst.

C'est normal ? 

![image](https://user-images.githubusercontent.com/99041220/152578554-fbe332c2-7767-4875-a14b-64024bb43e50.png)

**Comment by benjaminguinaudeau** [comment]
Ceux dans /inst provenaient d'une précédente version. 

Cela devrait être maintenant réglé. Mercid e l'avoir noté.
